<?php

namespace Database\Seeders;

use App\Models\Tip;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TipSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get or create an admin user
        $admin = User::whereHas('roles', function ($query) {
            $query->where('name', 'admin');
        })->first();

        if (!$admin) {
            // If no admin exists, create one
            $admin = User::create([
                'name' => 'Admin User',
                'email' => 'admin@example.com',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'whatsapp_number' => '+2348000000000',
                'location' => 'Lagos, Nigeria',
                'referral_code' => 'ADMIN001',
            ]);
            // Note: You might need to assign admin role here depending on your role system
        }

        // Create specific tips with meaningful content
        $tips = [
            [
                'title' => '5 Essential WhatsApp Business Features Every Entrepreneur Should Use',
                'content' => "WhatsApp Business has revolutionized how entrepreneurs connect with their customers. Here are five game-changing features that can transform your business communication:\n\n1. **Business Profile**: Create a professional presence with your business description, contact information, and website link. This builds trust and credibility with potential customers.\n\n2. **Automated Messages**: Set up welcome messages, away messages, and quick replies to ensure customers always receive timely responses, even when you're busy.\n\n3. **Catalog Feature**: Showcase your products or services directly within WhatsApp. Customers can browse, ask questions, and make purchases without leaving the app.\n\n4. **Labels and Organization**: Use labels to categorize your chats - new customers, pending orders, completed sales. This helps you stay organized and follow up effectively.\n\n5. **WhatsApp Web**: Manage your business conversations from your computer, making it easier to type longer messages and handle multiple conversations simultaneously.\n\nImplementing these features can significantly improve your customer service and boost sales. Start with one feature at a time and gradually incorporate others as you become more comfortable.",
                'status' => Tip::STATUS_PUBLISHED,
                'published_at' => now()->subDays(2),
                'claps' => 45,
            ],
            [
                'title' => 'Building Your Personal Brand: Why Authenticity Beats Perfection',
                'content' => "In today's digital world, personal branding isn't just for celebrities and influencers - it's essential for every professional and entrepreneur. But here's the secret: authenticity trumps perfection every time.\n\n**Why Authenticity Matters:**\n\nPeople connect with real stories, not polished facades. When you share your genuine experiences, including failures and lessons learned, you create deeper connections with your audience.\n\n**Practical Steps to Build Authentic Personal Brand:**\n\n• Share your journey, including the ups and downs\n• Be consistent in your messaging across all platforms\n• Engage genuinely with your community\n• Provide value through your expertise and experiences\n• Stay true to your values, even when it's challenging\n\n**The Power of Vulnerability:**\n\nSharing your struggles and how you overcame them makes you relatable. It shows that success isn't about being perfect - it's about persistence, learning, and growth.\n\n**Remember:** Your personal brand is not about creating a perfect image. It's about being genuinely helpful, consistently valuable, and authentically you. People will remember how you made them feel, not how perfect you appeared.\n\nStart today by sharing one authentic story about your professional journey. You'll be surprised by the positive response you receive.",
                'status' => Tip::STATUS_PUBLISHED,
                'published_at' => now()->subDays(5),
                'claps' => 78,
            ],
            [
                'title' => 'The Psychology of Pricing: How to Price Your Services for Maximum Profit',
                'content' => "Pricing your services correctly is both an art and a science. Understanding the psychology behind pricing can dramatically impact your business success.\n\n**The Anchoring Effect:**\n\nAlways present your highest-priced option first. This creates an 'anchor' that makes your other options seem more reasonable by comparison.\n\n**The Power of 9:**\n\nPrices ending in 9 ($99, $199) are perceived as significantly lower than round numbers ($100, $200), even though the difference is minimal.\n\n**Value-Based Pricing Strategy:**\n\nInstead of pricing based on time, price based on the value you provide. Ask yourself: 'What is the result worth to my client?' A $5,000 strategy that saves a business $50,000 is incredibly valuable.\n\n**The Decoy Effect:**\n\nOffer three pricing tiers. Make the middle option your target sale - it should offer the best value. The highest tier makes the middle seem reasonable, while the lowest tier makes the middle seem premium.\n\n**Confidence in Your Pricing:**\n\nYour confidence in your pricing affects how clients perceive value. If you're uncomfortable with your prices, clients will sense it. Practice stating your prices with conviction.\n\n**Testing and Adjusting:**\n\nDon't be afraid to test different price points. Start higher than you think - you can always come down, but it's much harder to raise prices later.\n\nRemember: Cheap prices attract cheap clients. Price for the clients you want to work with, not the ones you think you deserve.",
                'status' => Tip::STATUS_PUBLISHED,
                'published_at' => now()->subDays(7),
                'claps' => 92,
            ],
            [
                'title' => 'Mastering Time Management: The Pomodoro Technique for Entrepreneurs',
                'content' => "Time management is crucial for entrepreneurial success. The Pomodoro Technique is a simple yet powerful method that can transform your productivity.\n\n**How It Works:**\n\n1. Choose a task to work on\n2. Set a timer for 25 minutes\n3. Work on the task until the timer rings\n4. Take a 5-minute break\n5. Repeat 3-4 times, then take a longer 15-30 minute break\n\n**Why It's Effective:**\n\n• Creates urgency and focus\n• Prevents burnout with regular breaks\n• Makes large tasks feel manageable\n• Helps track how long tasks actually take\n\n**Tips for Success:**\n\n• Turn off all notifications during work periods\n• Use the breaks to move around or stretch\n• Don't check emails or social media during breaks\n• Adjust the timing to fit your attention span\n\nStart with just one Pomodoro session today and gradually build the habit. You'll be amazed at how much more you can accomplish with focused, uninterrupted work time.",
                'status' => Tip::STATUS_PUBLISHED,
                'published_at' => now()->subDays(10),
                'claps' => 67,
            ],
            [
                'title' => 'Building Customer Loyalty: 7 Strategies That Actually Work',
                'content' => "Customer loyalty isn't just about having a good product - it's about creating an experience that keeps customers coming back. Here are seven proven strategies:\n\n**1. Personalized Communication**\nUse customer names and reference their purchase history. Make them feel seen and valued.\n\n**2. Consistent Quality**\nNever compromise on quality. One bad experience can undo months of good ones.\n\n**3. Surprise and Delight**\nOccasional unexpected bonuses - a discount, free shipping, or small gift - create memorable moments.\n\n**4. Listen and Respond**\nActively seek feedback and show customers you're implementing their suggestions.\n\n**5. Loyalty Programs**\nReward repeat customers with points, discounts, or exclusive access to new products.\n\n**6. Exceptional Customer Service**\nTrain your team to go above and beyond. Solve problems quickly and with empathy.\n\n**7. Community Building**\nCreate spaces where customers can connect with each other and your brand.\n\nRemember: It costs 5-25 times more to acquire a new customer than to retain an existing one. Invest in loyalty.",
                'status' => Tip::STATUS_PUBLISHED,
                'published_at' => now()->subDays(12),
                'claps' => 89,
            ],
            [
                'title' => 'The Art of Networking: Quality Over Quantity',
                'content' => "Effective networking isn't about collecting business cards - it's about building genuine relationships that provide mutual value.\n\n**Before the Event:**\n\n• Research attendees and speakers\n• Set specific goals (3-5 meaningful connections)\n• Prepare your elevator pitch\n• Bring plenty of business cards\n\n**During the Event:**\n\n• Listen more than you talk\n• Ask thoughtful questions\n• Offer help before asking for it\n• Take notes about people you meet\n• Follow up on conversations\n\n**After the Event:**\n\n• Connect within 24-48 hours\n• Reference specific conversation points\n• Offer value in your follow-up\n• Schedule coffee meetings with key connections\n\n**Online Networking:**\n\n• Engage meaningfully on LinkedIn\n• Share valuable content regularly\n• Comment thoughtfully on others' posts\n• Join relevant industry groups\n\n**The Golden Rule:**\nAlways think about how you can help others first. When you lead with value, opportunities naturally follow.",
                'status' => Tip::STATUS_PUBLISHED,
                'published_at' => now()->subDays(15),
                'claps' => 73,
            ],
            [
                'title' => 'Digital Marketing on a Budget: Maximum Impact, Minimum Spend',
                'content' => "You don't need a huge budget to create effective digital marketing campaigns. Here's how to maximize your impact with minimal spend:\n\n**Content Marketing (Free):**\n\n• Start a blog and write valuable content\n• Create how-to videos using your phone\n• Share behind-the-scenes content\n• Repurpose content across platforms\n\n**Social Media Strategy:**\n\n• Focus on 1-2 platforms where your audience is active\n• Post consistently (quality over quantity)\n• Engage with your community daily\n• Use relevant hashtags strategically\n\n**Email Marketing:**\n\n• Build an email list from day one\n• Send weekly valuable content\n• Segment your audience for targeted messages\n• Use free tools like Mailchimp to start\n\n**Partnerships and Collaborations:**\n\n• Partner with complementary businesses\n• Guest post on relevant blogs\n• Participate in podcast interviews\n• Cross-promote with other entrepreneurs\n\n**Measure and Optimize:**\n\n• Track key metrics (engagement, conversions)\n• Test different approaches\n• Double down on what works\n• Eliminate what doesn't\n\nRemember: Consistency and value beat big budgets every time.",
                'status' => Tip::STATUS_PUBLISHED,
                'published_at' => now()->subDays(18),
                'claps' => 95,
            ],
            [
                'title' => 'Financial Planning for Entrepreneurs: Building a Safety Net',
                'content' => "Financial planning is crucial for entrepreneurial success. Here's how to build a solid financial foundation:\n\n**Emergency Fund:**\n\n• Save 6-12 months of expenses\n• Keep it in a separate, easily accessible account\n• Don't touch it unless it's a true emergency\n• Build it gradually - even ₦5,000/month helps\n\n**Separate Business and Personal Finances:**\n\n• Open a dedicated business bank account\n• Get a business credit card\n• Track all business expenses\n• Pay yourself a regular salary\n\n**Cash Flow Management:**\n\n• Create monthly cash flow projections\n• Invoice promptly and follow up on payments\n• Negotiate payment terms with suppliers\n• Keep 2-3 months of operating expenses in business account\n\n**Tax Planning:**\n\n• Set aside 25-30% of income for taxes\n• Keep detailed records of all expenses\n• Work with a qualified accountant\n• Make quarterly tax payments if required\n\n**Investment Strategy:**\n\n• Reinvest profits back into the business initially\n• Diversify investments as business grows\n• Consider retirement planning early\n• Don't put all eggs in one basket\n\nFinancial discipline today creates freedom tomorrow.",
                'status' => Tip::STATUS_PUBLISHED,
                'published_at' => now()->subDays(20),
                'claps' => 81,
            ],
            [
                'title' => 'Leadership Skills Every Entrepreneur Must Develop',
                'content' => "Great entrepreneurs are great leaders. Here are essential leadership skills to develop:\n\n**Communication:**\n\n• Be clear and concise in your messaging\n• Listen actively to your team\n• Provide regular feedback\n• Adapt your communication style to different people\n\n**Decision Making:**\n\n• Gather relevant information quickly\n• Consider multiple perspectives\n• Make decisions promptly\n• Take responsibility for outcomes\n\n**Emotional Intelligence:**\n\n• Understand your own emotions\n• Recognize emotions in others\n• Manage stress effectively\n• Show empathy and compassion\n\n**Vision and Strategy:**\n\n• Develop a clear vision for your business\n• Communicate the vision effectively\n• Break down big goals into actionable steps\n• Adapt strategy based on market feedback\n\n**Team Building:**\n\n• Hire people who complement your skills\n• Create a positive work culture\n• Delegate effectively\n• Recognize and reward good performance\n\n**Continuous Learning:**\n\n• Stay curious and open to new ideas\n• Learn from failures and mistakes\n• Seek feedback from mentors and peers\n• Invest in your own development\n\nLeadership is not about being perfect - it's about being authentic, decisive, and committed to growth.",
                'status' => Tip::STATUS_PUBLISHED,
                'published_at' => now()->subDays(22),
                'claps' => 76,
            ],
            [
                'title' => 'Scaling Your Business: When and How to Grow',
                'content' => "Knowing when and how to scale your business is crucial for long-term success. Here's a strategic approach:\n\n**Signs You're Ready to Scale:**\n\n• Consistent revenue growth for 6+ months\n• Strong cash flow and financial stability\n• Proven business model and processes\n• Market demand exceeds your current capacity\n• Strong team and operational systems\n\n**Scaling Strategies:**\n\n**1. Operational Scaling:**\n• Automate repetitive processes\n• Implement better systems and tools\n• Standardize procedures\n• Improve efficiency before adding resources\n\n**2. Team Scaling:**\n• Hire strategically for key roles\n• Develop strong onboarding processes\n• Create clear job descriptions and expectations\n• Build a strong company culture\n\n**3. Market Scaling:**\n• Expand to new geographic markets\n• Target new customer segments\n• Develop new product lines\n• Explore new distribution channels\n\n**Common Scaling Mistakes:**\n\n• Scaling too fast without proper foundation\n• Neglecting company culture during growth\n• Not investing in systems and processes\n• Losing focus on core business\n\n**Key Metrics to Track:**\n\n• Customer acquisition cost\n• Customer lifetime value\n• Monthly recurring revenue\n• Employee productivity\n• Customer satisfaction\n\nScale smart, not just fast.",
                'status' => Tip::STATUS_PUBLISHED,
                'published_at' => now()->subDays(25),
                'claps' => 88,
            ],
            [
                'title' => 'Crisis Management: Turning Challenges into Opportunities',
                'content' => "Every business faces crises. How you handle them can make or break your company. Here's how to navigate challenges effectively:\n\n**Immediate Response (First 24-48 hours):**\n\n• Assess the situation objectively\n• Communicate with key stakeholders\n• Implement damage control measures\n• Document everything for future reference\n\n**Strategic Response:**\n\n• Develop multiple scenario plans\n• Focus on cash flow preservation\n• Communicate transparently with customers\n• Support your team through uncertainty\n\n**Finding Opportunities:**\n\n• Identify new market needs created by the crisis\n• Pivot your business model if necessary\n• Strengthen relationships with loyal customers\n• Invest in areas competitors are cutting\n\n**Building Resilience:**\n\n• Diversify revenue streams\n• Build stronger emergency funds\n• Develop flexible business processes\n• Create contingency plans for various scenarios\n\n**Communication During Crisis:**\n\n• Be honest and transparent\n• Communicate frequently with all stakeholders\n• Focus on solutions, not just problems\n• Show empathy and understanding\n\n**Learning and Growth:**\n\n• Conduct post-crisis analysis\n• Document lessons learned\n• Update business processes\n• Prepare better for future challenges\n\nRemember: Crises are temporary, but the lessons and resilience you build last forever.",
                'status' => Tip::STATUS_PUBLISHED,
                'published_at' => now()->subDays(28),
                'claps' => 94,
            ],
            [
                'title' => 'Work-Life Balance for Entrepreneurs: Myth or Reality?',
                'content' => "Work-life balance as an entrepreneur looks different from traditional employment, but it's absolutely achievable with the right approach:\n\n**Redefine Balance:**\n\n• Think integration, not separation\n• Focus on energy management, not just time\n• Align work with your natural rhythms\n• Create boundaries that work for your lifestyle\n\n**Time Management Strategies:**\n\n• Use time-blocking for different activities\n• Batch similar tasks together\n• Delegate or outsource non-essential work\n• Learn to say no to non-priority requests\n\n**Setting Boundaries:**\n\n• Define specific work hours\n• Create a dedicated workspace\n• Turn off notifications during personal time\n• Communicate boundaries to clients and team\n\n**Self-Care Essentials:**\n\n• Prioritize sleep (7-8 hours minimum)\n• Exercise regularly, even if just 20 minutes\n• Eat nutritious meals at regular times\n• Schedule time for hobbies and relaxation\n\n**Relationship Management:**\n\n• Schedule quality time with family and friends\n• Be present when you're with loved ones\n• Communicate your entrepreneurial journey\n• Ask for support when needed\n\n**Mental Health:**\n\n• Practice mindfulness or meditation\n• Seek professional help when needed\n• Connect with other entrepreneurs\n• Celebrate small wins along the way\n\nRemember: You can't pour from an empty cup. Taking care of yourself is taking care of your business.",
                'status' => Tip::STATUS_DRAFT,
                'published_at' => null,
                'claps' => 0,
            ],
            [
                'title' => 'The Future of E-commerce in Nigeria: Trends to Watch',
                'content' => "E-commerce in Nigeria is evolving rapidly. Here are key trends that will shape the future:\n\n**Mobile-First Commerce:**\n\n• Mobile payments are becoming mainstream\n• Social commerce through WhatsApp and Instagram\n• Mobile-optimized websites are essential\n• App-based shopping experiences\n\n**Payment Innovation:**\n\n• Digital wallets gaining adoption\n• Buy-now-pay-later services\n• Cryptocurrency payments emerging\n• Bank transfer integrations\n\n**Logistics Evolution:**\n\n• Last-mile delivery improvements\n• Drone delivery pilots\n• Pickup point networks\n• Same-day delivery in major cities\n\n**Social Commerce:**\n\n• Instagram and Facebook shopping\n• WhatsApp Business catalogs\n• Influencer-driven sales\n• Live streaming commerce\n\n**Personalization:**\n\n• AI-powered recommendations\n• Customized shopping experiences\n• Targeted marketing campaigns\n• Dynamic pricing strategies\n\n**Sustainability Focus:**\n\n• Eco-friendly packaging\n• Local sourcing preferences\n• Sustainable business practices\n• Green delivery options\n\n**Opportunities for Entrepreneurs:**\n\n• Niche market specialization\n• Local product focus\n• Technology integration\n• Customer experience innovation\n\nThe future belongs to businesses that adapt quickly and put customers first.",
                'status' => Tip::STATUS_DRAFT,
                'published_at' => null,
                'claps' => 0,
            ],
            [
                'title' => 'Building a Strong Company Culture in Remote Teams',
                'content' => "Remote work is here to stay. Building strong company culture in distributed teams requires intentional effort:\n\n**Foundation Elements:**\n\n• Define clear company values\n• Communicate mission and vision regularly\n• Create shared goals and objectives\n• Establish cultural norms and expectations\n\n**Communication Strategies:**\n\n• Regular team meetings and check-ins\n• Use multiple communication channels\n• Encourage informal conversations\n• Practice transparent communication\n\n**Team Building Activities:**\n\n• Virtual coffee chats and lunch meetings\n• Online team building games\n• Quarterly in-person meetups if possible\n• Celebrate achievements together\n\n**Performance and Recognition:**\n\n• Set clear performance expectations\n• Provide regular feedback\n• Recognize achievements publicly\n• Create career development opportunities\n\n**Work-Life Integration:**\n\n• Respect different time zones\n• Encourage flexible working hours\n• Promote mental health awareness\n• Support home office setups\n\n**Technology and Tools:**\n\n• Invest in collaboration tools\n• Ensure reliable internet and equipment\n• Provide technical support\n• Use project management systems\n\n**Onboarding Process:**\n\n• Create comprehensive onboarding programs\n• Assign mentors to new hires\n• Provide cultural orientation\n• Set up early wins and connections\n\nStrong culture drives performance, retention, and business success.",
                'status' => Tip::STATUS_ARCHIVED,
                'published_at' => now()->subDays(35),
                'claps' => 42,
            ]
        ];

        foreach ($tips as $tipData) {
            $tipData['author_id'] = $admin->id;
            $tipData['slug'] = Str::slug($tipData['title']);
            
            Tip::create($tipData);
        }

        // Create additional tips manually
        $additionalTips = [
            [
                'title' => 'Social Media Marketing on a Budget: Free Tools That Actually Work',
                'content' => "You don't need expensive tools to succeed on social media. Here are free resources that deliver real results:\n\n**Content Creation:**\n• Canva (free version) - Professional graphics\n• Unsplash - High-quality stock photos\n• GIMP - Free photo editing\n\n**Scheduling & Management:**\n• Buffer (free plan) - Schedule posts across platforms\n• Hootsuite (free tier) - Manage multiple accounts\n• Later (free version) - Visual content calendar\n\n**Analytics & Insights:**\n• Google Analytics - Track website traffic from social\n• Facebook Insights - Detailed page analytics\n• Instagram Insights - Built-in analytics tool\n\n**Content Ideas:**\n• Google Trends - Discover trending topics\n• Answer The Public - Find questions people ask\n• BuzzSumo (limited free) - See popular content\n\n**Strategy Tips:**\n- Focus on 2-3 platforms maximum\n- Post consistently rather than frequently\n- Engage authentically with your audience\n- Share valuable content, not just promotions\n\nSuccess comes from strategy and consistency, not expensive tools.",
                'status' => Tip::STATUS_PUBLISHED,
                'published_at' => now()->subDays(12),
                'claps' => 67,
            ],
            [
                'title' => 'Customer Retention: Why Keeping Customers is Cheaper Than Finding New Ones',
                'content' => "Acquiring new customers costs 5-25 times more than retaining existing ones. Here's how to build customer loyalty:\n\n**The Retention Advantage:**\n• Existing customers spend 67% more than new ones\n• Loyal customers refer others (free marketing)\n• Higher lifetime value means better ROI\n\n**Proven Retention Strategies:**\n\n1. **Exceptional Customer Service**\n   - Respond quickly to inquiries\n   - Go above and beyond expectations\n   - Train your team in empathy and problem-solving\n\n2. **Personalization**\n   - Remember customer preferences\n   - Send personalized recommendations\n   - Use their name in communications\n\n3. **Loyalty Programs**\n   - Reward repeat purchases\n   - Offer exclusive perks\n   - Create tiers for different customer levels\n\n4. **Regular Communication**\n   - Send valuable content, not just sales pitches\n   - Ask for feedback and act on it\n   - Celebrate milestones with customers\n\n5. **Surprise and Delight**\n   - Unexpected bonuses or discounts\n   - Handwritten thank you notes\n   - Early access to new products\n\n**Measuring Success:**\n- Track customer lifetime value\n- Monitor repeat purchase rates\n- Measure Net Promoter Score (NPS)\n\nInvest in your existing customers - they're your most valuable asset.",
                'status' => Tip::STATUS_PUBLISHED,
                'published_at' => now()->subDays(15),
                'claps' => 89,
            ],
            [
                'title' => 'Email Marketing Fundamentals: Building Lists That Convert',
                'content' => "Email marketing delivers the highest ROI of any digital marketing channel. Here's how to build and nurture an email list that converts:\n\n**List Building Strategies:**\n\n1. **Lead Magnets That Work**\n   - Free ebooks or guides\n   - Exclusive discounts\n   - Webinars or mini-courses\n   - Templates or checklists\n\n2. **Opt-in Placement**\n   - Website header and footer\n   - Blog post content upgrades\n   - Social media bio links\n   - Exit-intent popups\n\n**Email Types for Engagement:**\n\n• **Welcome Series** - Introduce your brand and set expectations\n• **Educational Content** - Share valuable tips and insights\n• **Product Updates** - Announce new features or services\n• **Customer Stories** - Build trust through testimonials\n• **Exclusive Offers** - Reward subscribers with special deals\n\n**Best Practices:**\n- Write compelling subject lines (aim for 30-50 characters)\n- Personalize beyond just using names\n- Mobile-optimize all emails (60% open on mobile)\n- Test send times and frequencies\n- Segment your list based on behavior and preferences\n\n**Avoiding the Spam Folder:**\n- Use double opt-in for quality subscribers\n- Maintain good sender reputation\n- Include clear unsubscribe options\n- Avoid spam trigger words\n\n**Key Metrics to Track:**\n- Open rates (aim for 20-25%)\n- Click-through rates (aim for 2-5%)\n- Conversion rates\n- List growth rate\n- Unsubscribe rate\n\nRemember: Quality over quantity. A smaller, engaged list is more valuable than a large, unresponsive one.",
                'status' => Tip::STATUS_PUBLISHED,
                'published_at' => now()->subDays(18),
                'claps' => 76,
            ],
            [
                'title' => 'Financial Planning for Small Business: Cash Flow Management Essentials',
                'content' => "Cash flow is the lifeblood of any business. Poor cash flow management is one of the top reasons small businesses fail. Here's how to stay on top of your finances:\n\n**Understanding Cash Flow:**\nCash flow is the movement of money in and out of your business. Positive cash flow means more money coming in than going out.\n\n**Cash Flow Forecasting:**\n\n1. **Track Everything**\n   - Record all income and expenses\n   - Use accounting software or spreadsheets\n   - Update daily or weekly\n\n2. **Project Future Cash Flow**\n   - Estimate upcoming sales\n   - Plan for seasonal variations\n   - Account for large expenses\n\n3. **Create Different Scenarios**\n   - Best case scenario\n   - Worst case scenario\n   - Most likely scenario\n\n**Improving Cash Flow:**\n\n• **Speed Up Receivables**\n  - Offer early payment discounts\n  - Send invoices immediately\n  - Follow up on overdue payments\n  - Consider factoring for immediate cash\n\n• **Manage Payables Strategically**\n  - Negotiate longer payment terms\n  - Take advantage of early payment discounts\n  - Prioritize critical suppliers\n\n• **Inventory Management**\n  - Avoid overstocking\n  - Implement just-in-time ordering\n  - Clear out slow-moving inventory\n\n**Emergency Preparedness:**\n- Maintain 3-6 months of operating expenses in reserve\n- Establish a line of credit before you need it\n- Build relationships with multiple suppliers\n- Diversify your customer base\n\n**Warning Signs:**\n- Consistently late payments to suppliers\n- Declining profit margins\n- Increasing accounts receivable\n- Relying heavily on credit\n\nRegular cash flow monitoring isn't just about survival - it's about positioning your business for growth opportunities.",
                'status' => Tip::STATUS_PUBLISHED,
                'published_at' => now()->subDays(20),
                'claps' => 54,
            ],
            [
                'title' => 'Networking Like a Pro: Building Meaningful Business Relationships',
                'content' => "Networking isn't about collecting business cards - it's about building genuine relationships that create mutual value. Here's how to network effectively:\n\n**Mindset Shift:**\nApproach networking with a 'give first' mentality. Focus on how you can help others rather than what you can get.\n\n**Before the Event:**\n\n1. **Research Attendees**\n   - Check the attendee list if available\n   - Identify 3-5 people you'd like to meet\n   - Prepare conversation starters\n\n2. **Set Clear Goals**\n   - Quality over quantity (aim for 3-5 meaningful connections)\n   - Define what success looks like\n   - Prepare your elevator pitch\n\n**During the Event:**\n\n• **Be Genuinely Interested**\n  - Ask open-ended questions\n  - Listen more than you talk\n  - Remember personal details\n\n• **Conversation Starters That Work**\n  - \"What brings you to this event?\"\n  - \"What's the most exciting project you're working on?\"\n  - \"What trends are you seeing in your industry?\"\n\n• **Exchange Information Meaningfully**\n  - Connect on LinkedIn immediately\n  - Take notes on business cards\n  - Suggest specific follow-up actions\n\n**After the Event:**\n\n1. **Follow Up Within 48 Hours**\n   - Send personalized LinkedIn messages\n   - Reference specific conversation points\n   - Suggest concrete next steps\n\n2. **Provide Value First**\n   - Share relevant articles or resources\n   - Make introductions to others in your network\n   - Offer your expertise or assistance\n\n**Virtual Networking Tips:**\n- Join industry-specific online communities\n- Participate in Twitter chats and LinkedIn discussions\n- Attend virtual events and webinars\n- Engage meaningfully with others' content\n\n**Long-term Relationship Building:**\n- Stay in touch regularly (not just when you need something)\n- Celebrate others' successes\n- Offer help without being asked\n- Be consistent and reliable\n\nRemember: The best networkers are the best givers. Focus on building relationships, not just collecting contacts.",
                'status' => Tip::STATUS_PUBLISHED,
                'published_at' => now()->subDays(22),
                'claps' => 43,
            ],
            [
                'title' => 'Content Marketing Strategy: Creating Content That Drives Results',
                'content' => "Content marketing is about creating valuable, relevant content that attracts and engages your target audience. Here's how to develop a winning strategy:\n\n**Foundation: Know Your Audience**\n\n1. **Create Buyer Personas**\n   - Demographics and psychographics\n   - Pain points and challenges\n   - Goals and aspirations\n   - Preferred content formats\n\n2. **Map the Customer Journey**\n   - Awareness stage content\n   - Consideration stage content\n   - Decision stage content\n   - Retention and advocacy content\n\n**Content Planning:**\n\n• **Content Audit**\n  - Analyze existing content performance\n  - Identify content gaps\n  - Repurpose high-performing content\n\n• **Editorial Calendar**\n  - Plan content themes by month\n  - Balance educational and promotional content\n  - Align with business goals and seasons\n\n• **Content Mix (80/20 Rule)**\n  - 80% valuable, educational content\n  - 20% promotional content\n\n**Content Types That Work:**\n\n1. **Educational Content**\n   - How-to guides and tutorials\n   - Industry insights and trends\n   - Tips and best practices\n\n2. **Social Proof**\n   - Customer success stories\n   - Case studies\n   - User-generated content\n\n3. **Behind-the-Scenes**\n   - Company culture content\n   - Process explanations\n   - Team spotlights\n\n**Distribution Strategy:**\n\n• **Owned Media**\n  - Your website and blog\n  - Email newsletters\n  - Podcasts or video channels\n\n• **Earned Media**\n  - Guest posting\n  - Podcast appearances\n  - Media coverage\n\n• **Paid Media**\n  - Social media advertising\n  - Content promotion\n  - Influencer partnerships\n\n**Measuring Success:**\n- Traffic and engagement metrics\n- Lead generation and conversion rates\n- Brand awareness and sentiment\n- Customer lifetime value\n\n**Content Creation Tips:**\n- Start with one format and master it\n- Repurpose content across multiple channels\n- Use storytelling to make content memorable\n- Include clear calls-to-action\n- Optimize for search engines\n\nConsistency beats perfection. Start creating valuable content regularly, and refine your strategy based on what resonates with your audience.",
                'status' => Tip::STATUS_DRAFT,
                'published_at' => null,
                'claps' => 0,
            ],
            [
                'title' => 'Leadership in Crisis: Guiding Your Team Through Uncertainty',
                'content' => "Crisis situations test leadership like nothing else. Whether it's economic downturns, industry disruptions, or global events, strong leadership can make the difference between survival and failure.\n\n**Crisis Leadership Principles:**\n\n1. **Communicate Transparently**\n   - Share what you know and what you don't\n   - Provide regular updates\n   - Be honest about challenges\n   - Acknowledge emotions and concerns\n\n2. **Make Decisions Quickly**\n   - Gather available information rapidly\n   - Accept that perfect information isn't always possible\n   - Communicate decisions clearly\n   - Be prepared to adjust course\n\n3. **Focus on What You Can Control**\n   - Identify controllable vs. uncontrollable factors\n   - Channel energy into actionable solutions\n   - Help team focus on their sphere of influence\n\n**Supporting Your Team:**\n\n• **Emotional Support**\n  - Acknowledge stress and anxiety\n  - Provide mental health resources\n  - Encourage work-life balance\n  - Lead by example in self-care\n\n• **Practical Support**\n  - Clarify roles and expectations\n  - Provide necessary tools and resources\n  - Remove obstacles and bureaucracy\n  - Offer flexibility where possible\n\n• **Professional Development**\n  - Use downtime for training\n  - Cross-train team members\n  - Invest in skill development\n  - Prepare for post-crisis opportunities\n\n**Strategic Thinking in Crisis:**\n\n1. **Scenario Planning**\n   - Develop multiple future scenarios\n   - Create contingency plans\n   - Identify early warning indicators\n   - Build flexibility into operations\n\n2. **Opportunity Recognition**\n   - Look for market gaps created by crisis\n   - Identify ways to serve customers better\n   - Consider strategic partnerships\n   - Invest in innovation\n\n**Communication Framework:**\n\n• **What** - Clear facts and information\n• **Why** - Context and reasoning\n• **How** - Specific actions and next steps\n• **When** - Timelines and milestones\n• **Who** - Roles and responsibilities\n\n**Building Resilience:**\n- Celebrate small wins and progress\n- Maintain team traditions and culture\n- Encourage innovation and creativity\n- Learn from setbacks and adapt\n- Plan for recovery and growth\n\nRemember: Crisis reveals character. Use these challenging times to strengthen your leadership skills and build a more resilient organization.",
                'status' => Tip::STATUS_DRAFT,
                'published_at' => null,
                'claps' => 0,
            ],
            [
                'title' => 'Digital Transformation for Small Business: Where to Start',
                'content' => "Digital transformation isn't just for large corporations. Small businesses can leverage technology to compete more effectively and serve customers better. Here's your roadmap:\n\n**Assessment Phase:**\n\n1. **Current State Analysis**\n   - Map existing processes\n   - Identify pain points and inefficiencies\n   - Assess current technology stack\n   - Evaluate team digital skills\n\n2. **Goal Setting**\n   - Define specific business objectives\n   - Identify key performance indicators\n   - Set realistic timelines\n   - Allocate budget and resources\n\n**Priority Areas for Small Business:**\n\n• **Customer Experience**\n  - Online presence and website optimization\n  - Customer relationship management (CRM)\n  - Multi-channel communication\n  - Self-service options\n\n• **Operations Efficiency**\n  - Process automation\n  - Cloud-based collaboration tools\n  - Digital document management\n  - Inventory and supply chain optimization\n\n• **Data and Analytics**\n  - Customer data collection and analysis\n  - Performance dashboards\n  - Predictive analytics for decision-making\n  - Marketing attribution and ROI tracking\n\n**Implementation Strategy:**\n\n1. **Start Small**\n   - Choose one area for initial focus\n   - Pilot with a small team or process\n   - Learn and iterate before scaling\n   - Celebrate early wins\n\n2. **Technology Selection**\n   - Prioritize user-friendly solutions\n   - Consider integration capabilities\n   - Evaluate total cost of ownership\n   - Choose scalable platforms\n\n3. **Change Management**\n   - Involve team in planning process\n   - Provide comprehensive training\n   - Address resistance and concerns\n   - Create digital champions\n\n**Common Pitfalls to Avoid:**\n- Trying to digitize everything at once\n- Choosing technology before understanding needs\n- Underestimating training requirements\n- Ignoring cybersecurity considerations\n- Failing to measure and adjust\n\n**Quick Wins for Immediate Impact:**\n- Implement online scheduling systems\n- Automate invoice and payment processing\n- Use social media management tools\n- Adopt cloud-based file sharing\n- Set up basic analytics tracking\n\n**Building Digital Culture:**\n- Encourage experimentation\n- Reward digital innovation\n- Invest in ongoing learning\n- Share success stories\n- Stay curious about new technologies\n\nDigital transformation is a journey, not a destination. Start where you are, use what you have, and do what you can. The key is to begin and keep moving forward.",
                'status' => Tip::STATUS_DRAFT,
                'published_at' => null,
                'claps' => 0,
            ],
            [
                'title' => 'Sustainable Business Practices: Profit with Purpose',
                'content' => "Sustainability isn't just good for the planet - it's good for business. Companies with strong sustainability practices often see improved profitability, customer loyalty, and employee engagement.\n\n**Why Sustainability Matters:**\n\n• **Consumer Demand**\n  - 73% of consumers willing to pay more for sustainable products\n  - Millennials and Gen Z prioritize environmental responsibility\n  - Brand reputation increasingly tied to sustainability\n\n• **Cost Savings**\n  - Energy efficiency reduces operational costs\n  - Waste reduction improves margins\n  - Sustainable practices often increase efficiency\n\n• **Risk Management**\n  - Regulatory compliance and future-proofing\n  - Supply chain resilience\n  - Access to sustainable financing\n\n**Getting Started:**\n\n1. **Sustainability Audit**\n   - Assess current environmental impact\n   - Identify areas for improvement\n   - Set baseline measurements\n   - Benchmark against industry standards\n\n2. **Quick Wins**\n   - Switch to LED lighting\n   - Implement recycling programs\n   - Reduce paper usage\n   - Optimize heating and cooling\n\n3. **Strategic Initiatives**\n   - Sustainable sourcing policies\n   - Green product development\n   - Carbon footprint reduction\n   - Circular economy principles\n\n**Implementation Areas:**\n\n• **Operations**\n  - Energy management systems\n  - Waste reduction and recycling\n  - Water conservation\n  - Sustainable transportation\n\n• **Supply Chain**\n  - Vendor sustainability requirements\n  - Local sourcing when possible\n  - Ethical labor practices\n  - Packaging optimization\n\n• **Products/Services**\n  - Eco-friendly design principles\n  - Product lifecycle assessment\n  - Repair and refurbishment programs\n  - Digital alternatives to physical products\n\n**Measuring Impact:**\n- Carbon footprint tracking\n- Waste diversion rates\n- Energy consumption metrics\n- Water usage monitoring\n- Sustainable sourcing percentages\n\n**Communication Strategy:**\n- Be authentic and transparent\n- Share progress and challenges\n- Avoid greenwashing\n- Engage stakeholders in sustainability journey\n- Celebrate milestones and achievements\n\n**Business Benefits:**\n- Reduced operational costs\n- Enhanced brand reputation\n- Improved employee morale\n- Access to new markets\n- Increased customer loyalty\n- Better risk management\n\nSustainability is not a destination but a continuous journey of improvement. Start with small steps and build momentum over time.",
                'status' => Tip::STATUS_ARCHIVED,
                'published_at' => now()->subDays(30),
                'claps' => 12,
            ],
            [
                'title' => 'Remote Work Management: Leading Distributed Teams Effectively',
                'content' => "Remote work is here to stay. Successfully managing distributed teams requires new skills, tools, and approaches. Here's how to lead effectively in a remote environment:\n\n**Building Remote Culture:**\n\n1. **Clear Communication Standards**\n   - Define response time expectations\n   - Choose appropriate communication channels\n   - Establish meeting etiquette\n   - Document decisions and processes\n\n2. **Trust and Autonomy**\n   - Focus on outcomes, not hours\n   - Give team members ownership\n   - Avoid micromanagement\n   - Provide clear expectations\n\n3. **Virtual Team Building**\n   - Regular team check-ins\n   - Virtual coffee chats\n   - Online team activities\n   - Celebrate achievements together\n\n**Essential Tools and Systems:**\n\n• **Communication**\n  - Video conferencing (Zoom, Teams)\n  - Instant messaging (Slack, Teams)\n  - Asynchronous communication tools\n  - Digital whiteboarding\n\n• **Collaboration**\n  - Project management platforms\n  - Shared document systems\n  - Version control systems\n  - Time tracking tools\n\n• **Productivity**\n  - Task management apps\n  - Calendar scheduling tools\n  - Focus and wellness apps\n  - Virtual private networks (VPN)\n\n**Managing Performance:**\n\n1. **Goal Setting**\n   - Use SMART goals framework\n   - Regular check-ins and updates\n   - Quarterly performance reviews\n   - Career development planning\n\n2. **Feedback and Recognition**\n   - Provide regular, specific feedback\n   - Recognize achievements publicly\n   - Address issues promptly\n   - Create peer recognition systems\n\n**Overcoming Remote Challenges:**\n\n• **Communication Gaps**\n  - Over-communicate important information\n  - Use multiple channels for critical messages\n  - Encourage questions and clarification\n  - Regular pulse surveys\n\n• **Isolation and Loneliness**\n  - Schedule regular one-on-ones\n  - Create virtual social spaces\n  - Encourage informal interactions\n  - Support mental health and wellness\n\n• **Work-Life Balance**\n  - Respect boundaries and time zones\n  - Encourage breaks and time off\n  - Model healthy work habits\n  - Provide flexibility when possible\n\n**Best Practices:**\n- Start meetings with personal check-ins\n- Use video when possible for important discussions\n- Document everything for transparency\n- Be intentional about inclusion\n- Invest in team member home office setups\n- Provide professional development opportunities\n\nRemote work success requires intentional effort and continuous adaptation. Focus on building strong relationships and clear processes to create a thriving distributed team.",
                'status' => Tip::STATUS_ARCHIVED,
                'published_at' => now()->subDays(35),
                'claps' => 8,
            ]
        ];

        foreach ($additionalTips as $tipData) {
            $tipData['author_id'] = $admin->id;
            $tipData['slug'] = Str::slug($tipData['title']);
            
            Tip::create($tipData);
        }
    }
}