<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vouchers Export</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            margin: 0;
            padding: 20px;
            color: #333;
            line-height: 1.4;
        }
        
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #007bff;
            padding-bottom: 20px;
        }
        
        .header h1 {
            color: #007bff;
            margin: 0;
            font-size: 28px;
        }
        
        .header p {
            margin: 5px 0;
            color: #666;
        }
        
        .summary {
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 30px;
            border-left: 4px solid #007bff;
        }
        
        .summary h3 {
            margin-top: 0;
            color: #007bff;
        }
        
        .voucher-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 20px;
            margin-bottom: 30px;
        }
        
        .voucher-card {
            border: 2px solid #dee2e6;
            border-radius: 8px;
            padding: 15px;
            background-color: #fff;
            page-break-inside: avoid;
        }
        
        .voucher-card.active {
            border-color: #28a745;
            background-color: #f8fff9;
        }
        
        .voucher-card.redeemed {
            border-color: #ffc107;
            background-color: #fffdf5;
        }
        
        .voucher-card.expired {
            border-color: #dc3545;
            background-color: #fff5f5;
        }
        
        .voucher-card.cancelled {
            border-color: #6c757d;
            background-color: #f8f9fa;
        }
        
        .voucher-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 10px;
            border-bottom: 1px solid #dee2e6;
            padding-bottom: 8px;
        }
        
        .voucher-code {
            font-family: 'Courier New', monospace;
            font-size: 16px;
            font-weight: bold;
            color: #007bff;
        }
        
        .voucher-status {
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 12px;
            font-weight: bold;
            text-transform: uppercase;
        }
        
        .status-active {
            background-color: #28a745;
            color: white;
        }
        
        .status-redeemed {
            background-color: #ffc107;
            color: #212529;
        }
        
        .status-expired {
            background-color: #dc3545;
            color: white;
        }
        
        .status-cancelled {
            background-color: #6c757d;
            color: white;
        }
        
        .voucher-amount {
            font-size: 20px;
            font-weight: bold;
            color: #28a745;
            margin: 8px 0;
        }
        
        .voucher-details {
            font-size: 12px;
            color: #666;
        }
        
        .voucher-details div {
            margin: 3px 0;
        }
        
        .voucher-description {
            margin-top: 8px;
            font-style: italic;
            color: #555;
            font-size: 11px;
        }
        
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 12px;
            color: #666;
            border-top: 1px solid #dee2e6;
            padding-top: 20px;
        }
        
        .page-break {
            page-break-before: always;
        }
        
        @media print {
            body {
                margin: 0;
                padding: 15px;
            }
            
            .voucher-grid {
                grid-template-columns: repeat(2, 1fr);
                gap: 15px;
            }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Vouchers Export</h1>
        <p><strong>Generated:</strong> {{ $generated_at->format('F j, Y \\a\\t g:i A') }}</p>
        <p><strong>Generated by:</strong> {{ $generated_by }}</p>
        @if(isset($filter) && $filter !== 'all')
            <p><strong>Filter:</strong> {{ ucfirst($filter) }} vouchers only</p>
        @endif
    </div>
    
    <div class="summary">
        <h3>Export Summary</h3>
        <div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px;">
            <div>
                <strong>Total Vouchers:</strong><br>
                {{ $vouchers->count() }}
            </div>
            <div>
                <strong>Total Value:</strong><br>
                ₦{{ number_format($vouchers->where('currency', 'NGN')->sum('amount'), 2) }}
            </div>
            <div>
                <strong>Active:</strong><br>
                {{ $vouchers->where('status', 'active')->count() }}
            </div>
            <div>
                <strong>Redeemed:</strong><br>
                {{ $vouchers->where('status', 'redeemed')->count() }}
            </div>
        </div>
    </div>
    
    <div class="voucher-grid">
        @foreach($vouchers as $index => $voucher)
            @if($index > 0 && $index % 10 === 0)
                <div class="page-break"></div>
            @endif
            
            <div class="voucher-card {{ $voucher->status }}">
                <div class="voucher-header">
                    <div class="voucher-code">{{ $voucher->code }}</div>
                    <div class="voucher-status status-{{ $voucher->status }}">
                        {{ ucfirst($voucher->status) }}
                    </div>
                </div>
                
                <div class="voucher-amount">
                    @if($voucher->currency === 'NGN')
                        ₦{{ number_format($voucher->amount, 2) }}
                    @else
                        {{ number_format($voucher->amount) }} {{ $voucher->currency }}
                    @endif
                </div>
                
                <div class="voucher-details">
                    <div><strong>Created:</strong> {{ $voucher->created_at->format('M j, Y') }}</div>
                    
                    @if($voucher->expires_at)
                        <div><strong>Expires:</strong> {{ $voucher->expires_at->format('M j, Y') }}</div>
                    @else
                        <div><strong>Expires:</strong> Never</div>
                    @endif
                    
                    @if($voucher->batch_id)
                        <div><strong>Batch:</strong> {{ $voucher->batch_id }}</div>
                    @endif
                    
                    @if($voucher->createdBy)
                        <div><strong>Created by:</strong> {{ $voucher->createdBy->name }}</div>
                    @endif
                    
                    @if($voucher->status === 'redeemed' && $voucher->redeemedBy)
                        <div><strong>Redeemed by:</strong> {{ $voucher->redeemedBy->name }}</div>
                        <div><strong>Redeemed on:</strong> {{ $voucher->redeemed_at->format('M j, Y') }}</div>
                    @endif
                </div>
                
                @if($voucher->description)
                    <div class="voucher-description">
                        {{ $voucher->description }}
                    </div>
                @endif
            </div>
        @endforeach
    </div>
    
    <div class="footer">
        <p>This document contains {{ $vouchers->count() }} voucher(s) exported from the admin panel.</p>
        <p>Generated on {{ $generated_at->format('F j, Y \\a\\t g:i A') }} by {{ $generated_by }}</p>
        <p><strong>Confidential:</strong> This document contains sensitive voucher information. Handle with care.</p>
    </div>
</body>
</html>